import { SolarProject } from './types';

// INSTRUCCIONES:
// Simplemente reemplaza la propiedad 'imageUrl' con el enlace directo a tu imagen (como el ejemplo de Athos).

export const SOLAR_PROJECTS: SolarProject[] = [
  {
    id: 'athos',
    name: 'Athos 1 & 2',
    location: 'California',
    stateCode: 'California',
    capacityMW: 650,
    coordinates: { long: -115.5, lat: 33.8 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/ATHOS-1-AND-2-CA.jpg',
  },
  {
    id: 'edward',
    name: 'Edward & Sanborn',
    location: 'California',
    stateCode: 'California',
    capacityMW: 970,
    coordinates: { long: -118.0, lat: 35.0 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/EDWARD-AND-SANBORN-CA.png',
  },
  {
    id: 'desert-sunlight',
    name: 'Desert Sunlight',
    location: 'California',
    stateCode: 'California',
    capacityMW: 550,
    coordinates: { long: -115.0, lat: 32.8 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/DESERT-SUNLIGHT-CA.jpg',
  },
  {
    id: 'quail-ranch',
    name: 'Quail Ranch',
    location: 'New Mexico',
    stateCode: 'New Mexico',
    capacityMW: 128,
    coordinates: { long: -106.0, lat: 34.0 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/QUAIL-RANCH-NM.jpg',
  },
  {
    id: 'horizon',
    name: 'Horizon',
    location: 'Texas',
    stateCode: 'Texas',
    capacityMW: 200,
    coordinates: { long: -102.5, lat: 31.5 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/HORIZON-TX.jpg',
  },
  {
    id: 'lumina',
    name: 'Lumina 1 & 2',
    location: 'Texas',
    stateCode: 'Texas',
    capacityMW: 830,
    coordinates: { long: -98.0, lat: 29.5 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/LUMINA-1-AND-2-TX.jpg',
  },
  {
    id: 'kelson',
    name: 'Kelson 1 & 2',
    location: 'Missouri',
    stateCode: 'Missouri',
    capacityMW: 430,
    coordinates: { long: -92.5, lat: 38.5 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/KELSO-1-2-MO.jpg',
  },
  {
    id: 'lafitte',
    name: 'Lafitte',
    location: 'Louisiana',
    stateCode: 'Louisiana',
    capacityMW: 100,
    coordinates: { long: -91.5, lat: 30.5 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/LAFITTE-LA.jpg',
  },
  {
    id: 'snipesville',
    name: 'Snipesville',
    location: 'Georgia',
    stateCode: 'Georgia',
    capacityMW: 300,
    coordinates: { long: -82.6, lat: 31.8 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/SNIPESVILLE-GA.jpg',
  },
  {
    id: 'harmony',
    name: 'Harmony 2 Storey Bend',
    location: 'Florida',
    stateCode: 'Florida',
    capacityMW: 150,
    coordinates: { long: -81.5, lat: 28.5 },
    imageUrl: 'https://administrator7381d8184c-okltg.wpcomstaging.com/wp-content/uploads/2025/11/HARMONY-2-STOREY-BEND-FL.jpg',
  },
];